### ISSUE TITLE
`private$printClass()` should get `addTab` argument

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.Utility#29]
Then `private$printClass()` should be fixed ;) We should use general functions if we already have them, instead of having "custom solutions" in every file.

_Originally posted by @PavelBal in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/690#discussion_r792588530_

**Comment by IndrajeetPatil** [comment]
Damn, this is the wrong repo.

I don't have the rights to do. @msevestre, can you move this issue to this repo please:
https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils

**Comment by PavelBal** [comment]
Just open it in ospsuite-r repo and close here..

**Comment by PavelBal** [comment]
Oh I cannot close, too :D

**Comment by IndrajeetPatil** [comment]
Closed in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/27
